models/enumTipoRuc.py
import enum
class enumTipoRuc (enum.Enum):
    EDUCATIVO = 'EDUCATIVO'
    PROFESIONAL = 'PROFESIONAL'

    def getValues(self):
        return self.value

    def __str__(self) -> str:
        return self.value

models/factura.py
from models.enumTipoRuc import enumTipoRuc

class Factura():
    def __init__(self):
        self.__id = 0
        self.__usuario = ''
        self.__ruc = ''
        self.__monto = 0.00
        self.__tipo_ruc = enumTipoRuc

    @property
    def _id(self):
        return self.__id

    @_id.setter
    def _id(self, value):
        self.__id = value

    @property
    def _usuario(self):
        return self.__usuario

    @_usuario.setter
    def _usuario(self, value):
        self.__usuario = value

    @property
    def _ruc(self):
        return self.__ruc

    @_ruc.setter
    def _ruc(self, value):
        self.__ruc = value

    @property
    def _monto(self):
        return self.__monto

    @_monto.setter
    def _monto(self, value):
        self.__monto = value

    @property
    def _tipo_ruc(self):
        return self.__tipo_ruc

    @_tipo_ruc.setter
    def _tipo_ruc(self, value):
        self.__tipo_ruc = value

    @property
    def serializer(self):
        return {
            'id': self._id,
            'usuario': self._usuario,
            'ruc': self._ruc,
            'monto': self._monto,
            'tipo_ruc': self._tipo_ruc.__str__()
        }

    def deserializer(self, data):
        self._id = data['id']
        self._usuario = data['usuario']
        self._ruc = data['ruc']
        self._monto = data['monto']
        self._tipo_ruc = data['tipo_ruc']
        return self

models/retencion.py
from models.factura import Factura
from controls.tda.stack.stack import Stack

class Retencion:
    def __init__(self):
        self.__id = 0 
        self.__historialRetenciones = ''

    @property
    def _id(self):
        return self.__id

    @_id.setter
    def _id(self, value):
        self.__id = value

    @property
    def _historialRetenciones(self):
        return self.__historialRetenciones

    @_historialRetenciones.setter
    def _historialRetenciones(self, value):
        self.__historialRetenciones = value

    def calcularRetencion(self, factura: Factura) -> float:
        retencion = 0.0
        if factura._tipo_ruc == "EDUCATIVO":
            retencion = factura._monto * 0.08
        elif factura._tipo_ruc == "PROFESIONAL":
            retencion = factura._monto * 0.1
        return round(retencion, 2)
    
    def generarRetencion(self, factura: Factura):
        retencion = self.calcularRetencion(factura)
        self.__historialRetenciones.push({"factura": factura.serializer, "retencion": retencion})
        return factura
       
    @property
    def printHistorial(self):
        print('Historial de retenciones:')
        self.__historialRetenciones.print
        print('')


    @property
    def serializer(self):
        return {
            'id': self._id,
            'historialRetenciones': self._historialRetenciones.serializer
        }
    
    def deserializer(self, data):
        retencion = Retencion()
        retencion._id = data['id']
        retencion._historialRetenciones = data['historialRetenciones']
        return retencion
    
    

app.py
from flask import Flask

def create_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.config.Config')
    with app.app_context(): 
        from routes.router import router
        app.register_blueprint(router)
    return app

routes/api.py
from flask import Blueprint, jsonify, make_response, request
api = Blueprint('api', __name__)

@api.route('/')

def home():

    return make_response(
    jsonify({"msg":"OK", "code": 200}),
    200
    )

routes/router.py
from flask import Blueprint, jsonify, make_response, request, render_template, redirect
from controls.facturaDaoControl import FacturaDaoControl
from controls.retencionDaoControl import RetencionDaoControl

router = Blueprint('api', __name__)

@router.route('/')
def home():
    return render_template('template.html')


@router.route('/historial')
def lista_historial():
    hd = FacturaDaoControl()
    return render_template('factura/lista.html', lista = hd.to_dic())

@router.route('/historial/ver')
def ver_guardad():
    return render_template('factura/guardar.html')


@router.route('/historial/guardar', methods=['POST'])
def guardar_factura():

    factura = FacturaDaoControl()
    factura._factura._usuario = request.form['usuario']
    factura._factura._monto = request.form['monto']
    factura._factura._ruc = request.form['ruc']
    factura._factura._tipo_ruc = request.form['tipo_ruc']


    return redirect('/historial', code = 302)

views/main.py
import sys
sys.path.append('../')
import os
import psutil
from time import time

from controls.retencionDaoControl import RetencionDaoControl
from controls.facturaDaoControl import FacturaDaoControl


facturaDao = FacturaDaoControl()
#retencion = Retencion()
historial = RetencionDaoControl()


try:
    # tiempoInicio = time() 

    facturaDao._factura._monto = 1000.0
    facturaDao._factura._usuario = "Santiago"
    facturaDao._factura._ruc = "1234567890"
    facturaDao._factura._tipo_ruc = "PROFESIONAL"
    facturaDao._factura._fecha = "2021-10-10"
    facturaDao.save


    facturaDao._factura._monto = 2000.0
    facturaDao._factura._usuario = "Andres"
    facturaDao._factura._ruc = "1234567890"
    facturaDao._factura._tipo_ruc = "PROFESIONAL"
    facturaDao._factura._fecha = "2021-10-10"
    facturaDao.save

    facturaDao._factura._monto = 3000.0
    facturaDao._factura._usuario = "Anthony"
    facturaDao._factura._ruc = "1234567890"
    facturaDao._factura._tipo_ruc = "PROFESIONAL"
    facturaDao._factura._fecha = "2021-10-10"
    facturaDao.save

    facturaDao._factura._monto = 1000.0
    facturaDao._factura._usuario = "Cristhian"
    facturaDao._factura._ruc = "1234567890"
    facturaDao._factura._tipo_ruc = "EDUCATIVO"
    facturaDao._factura._fecha = "2021-10-10"
    facturaDao.save


    
    for factura in facturaDao.get_all:
        historial.generarRetencion(factura) #ESTO UTILIZA PILAS
   
    historial.printHistorial()
    historial.save()


    """ 
    tiempoFinal = time()
    print("Tiempo de ejecución: ", tiempoFinal - tiempoInicio)

    process = psutil.Process(os.getpid())
    memory_usage = process.memory_info().rss / 1024 ** 2
    print(f"La memoria utilizada por el programa es: {memory_usage} MB") """

except Exception as e:
    print(e)


    

templates/factura/guardar.html
{%extends "template.html"%}
{%block content%}
<h2 class="text-white">Agregar factura</h2>
<div class="booking-form-body">
    <a href="{{ url_for('api.lista_historial') }}" class="btn btn-success">VOLVER</a>       
    <form id="form" class="custom-form booking-form"  action="/historial/guardar" method="post" role="form">
        <div class="booking-form-body">
            <div class="row">
                <div class="col-lg-6 col-12">
                    <input type="text" name="usuario" class="form-control" placeholder="usuario" required>
                </div>
                <div class="col-lg-6 col-12">
                    <input type="text" name="monto" class="form-control" placeholder="Monto" required>
                </div>
                <div class="col-lg-6 col-12">
                    <input type="text" name="ruc" class="form-control" placeholder="RUC" required>
                </div>
                <div class="col-lg-6 col-12">
                    <select name="tipo_ruc" class="form-control" required>
                        <option value="">Seleccione el tipo de RUC</option>
                        <option value="EDUCATIVO">EDUCATIVO</option>
                        <option value="PROFESIONAL">PROFESIONAL</option>
                    </select>
                </div>
                <div class="col-lg-4 col-md-10 col-8 mx-auto mt-2">
                    <button id="boton" type="submit" class="form-control btn btn-success">Guardar</button>
                </div>
            </div>
        </div>
    </form> 
{% endblock %}

templates/factura/lista.html
{% extends "template.html"%}
{% block content%}
<h2 class = "text-white">Historial de Retenciones</h2>
<div class="booking-form-body">
    <a href="/historial/ver" class="btn btn-danger">AGREGAR</a>
    <table id="tabla" class="table text-white">
        <thead>
            <th>Factura Nro</th>
            <th>Usuario</th>
            <th>RUC</th>
            <th>Monto</th>
            <th>Tipo_RUC</th>
            <th>Retencion</th>
        </thead>
        <tbody>
            {% for item in lista%}
            <tr>
                <td>{{item.id}} </td>
                <td>{{item.usuario}} </td>
                <td>{{item.ruc}} </td>
                <td>{{item.monto}} </td>
                <td>{{item.tipo_ruc}} </td>
                <td>
                    {% if item.tipo_ruc == 'EDUCATIVO' %}
                        {{ item.monto * 0.08}}
                    {% else %}
                        {{ item.monto * 0.10 }}
                    {% endif %}
                 </td>
            </tr>
            {% endfor %}

        </tbody>
    </table> 
</div>
{% endblock %}

templates/template.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Practica</title>

        <!-- CSS FILES -->                
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200;0,400;0,600;0,700;1,200;1,700&display=swap" rel="stylesheet">
            
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">

        <link href="{{ url_for('static', filename='css/bootstrap-icons.css')}}" rel="stylesheet">

        <link href="{{ url_for('static', filename='css/vegas.min.css')}}" rel="stylesheet">

        <link href="{{ url_for('static', filename='css/tooplate-barista.css')}}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
   
        
    </head>
    
    <body class="reservation-page">
                
            <main>
                <nav class="navbar navbar-expand-lg">                
                    <div class="container">
                        <a class="navbar-brand d-flex align-items-center" href="{{ url_for('api.home') }}">
                            <img src="images/coffee-beans.png" class="navbar-brand-image img-fluid" alt="">
                            Retenciones 
                        </a>
        
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
        
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav ms-lg-auto">
                            
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('api.ver_guardad') }}">Registrar Factura</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('api.lista_historial') }}">Historial</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                

                <section class="booking-section section-padding">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-10 col-12 mx-auto">
                            <div class="booking-form-wrap">
                                <div class="row">
                                    
                                  {% block content %}{% endblock %}

                                    
                                </div>
                            </div>

                        </div>
                    </div>
                </section>


                <footer class="site-footer">
                    <div class="container">
                        <div class="row">

                            <div class="col-lg-4 col-12 me-auto">
                    

                              

                            </div>

                            <div class="col-lg-3 col-12 mt-4 mb-3 mt-lg-0 mb-lg-0">
                               

                                <p class="d-flex mb-1">
                                   
                                </p>

                                <p class="d-flex">
                                    

                                    
                                </p>
                            </div>


                            <div class="col-lg-5 col-12">
                                <em class="text-white d-block mb-4">Opening Hours.</em>

                                <ul class="opening-hours-list">
                                    <li class="d-flex">
                                        Monday - Friday
                                        <span class="underline"></span>

                                        <strong>9:00 - 18:00</strong>
                                    </li>

                                    <li class="d-flex">
                                        Saturday
                                        <span class="underline"></span>

                                        <strong>11:00 - 16:30</strong>
                                    </li>

                                    <li class="d-flex">
                                        Sunday
                                        <span class="underline"></span>

                                        <strong>Closed</strong>
                                    </li>
                                </ul>
                            </div>

                            <div class="col-lg-8 col-12 mt-4">
                                <p class="copyright-text mb-0">Copyright © Barista Cafe 2048 
                                    - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                            </div>

                    </div>
                </footer>
            </main>


        <!-- JAVASCRIPT FILES -->
        <script src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/jquery.sticky.js')}}"></script>
        <script src="{{ url_for('static', filename='js/vegas.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/custom.js')}}"></script>

    </body>
</html>